import type { Metadata } from "next";
import { Funnel_Display } from "next/font/google";
import "./globals.css";
import Navbar from "@/shared/Navbar";

const funnel = Funnel_Display({
  variable: "--font-funnel",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Floka",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${funnel.variable} h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        {/* Navbar */}
        <Navbar />
        <main>{children}</main>
        {/* Footer */}
      </body>
    </html>
  );
}
